export const FIRST_ROW = [
  { Backquote: { id: 'Backquote', name: '`', shiftName: '~' } },
  { Digit1: { id: 'Digit1', name: '1', shiftName: '!' } },
  { Digit2: { id: 'Digit2', name: '2', shiftName: '@' } },
  { Digit3: { id: 'Digit3', name: '3', shiftName: '#' } },
  { Digit4: { id: 'Digit4', name: '4', shiftName: '$' } },
  { Digit5: { id: 'Digit5', name: '5', shiftName: '%' } },
  { Digit6: { id: 'Digit6', name: '6', shiftName: '^' } },
  { Digit7: { id: 'Digit7', name: '7', shiftName: '&' } },
  { Digit8: { id: 'Digit8', name: '8', shiftName: '*' } },
  { Digit9: { id: 'Digit9', name: '9', shiftName: '(' } },
  { Digit0: { id: 'Digit0', name: '0', shiftName: ')' } },
  { Minus: { id: 'Minus', name: '-', shiftName: '_' } },
  { Equal: { id: 'Equal', name: '=', shiftName: '+' } },
  { Backspace: { id: 'Backspace', name: 'delete' } },
];

export const SECOND_ROW = [
  { Tab: { id: 'Tab', name: 'tab' } },
  { KeyQ: { id: 'KeyQ', name: 'q', shiftName: 'Q' } },
  { KeyW: { id: 'KeyW', name: 'w', shiftName: 'W' } },
  { KeyE: { id: 'KeyE', name: 'e', shiftName: 'E' } },
  { KeyR: { id: 'KeyR', name: 'r', shiftName: 'R' } },
  { KeyT: { id: 'KeyT', name: 't', shiftName: 'T' } },
  { KeyY: { id: 'KeyY', name: 'y', shiftName: 'Y' } },
  { KeyU: { id: 'KeyU', name: 'u', shiftName: 'U' } },
  { KeyI: { id: 'KeyI', name: 'i', shiftName: 'I' } },
  { KeyO: { id: 'KeyO', name: 'o', shiftName: 'O' } },
  { KeyP: { id: 'KeyP', name: 'p', shiftName: 'P' } },
  { BracketLeft: { id: 'BracketLeft', name: '[', shiftName: '{' } },
  { BracketRight: { id: 'BracketRight', name: ']', shiftName: '}' } },
  { Backslash: { id: 'Backslash', name: '\\', shiftName: '|' } },
];

export const THIRD_ROW = [
  { CapsLock: { id: 'CapsLock', name: 'caps lock' } },
  { KeyA: { id: 'KeyA', name: 'a', shiftName: 'A' } },
  { KeyS: { id: 'KeyS', name: 's', shiftName: 'S' } },
  { KeyD: { id: 'KeyD', name: 'd', shiftName: 'D' } },
  { KeyF: { id: 'KeyF', name: 'f', shiftName: 'F' } },
  { KeyG: { id: 'KeyG', name: 'g', shiftName: 'G' } },
  { KeyH: { id: 'KeyH', name: 'h', shiftName: 'H' } },
  { KeyJ: { id: 'KeyJ', name: 'j', shiftName: 'J' } },
  { KeyK: { id: 'KeyK', name: 'k', shiftName: 'K' } },
  { KeyL: { id: 'KeyL', name: 'l', shiftName: 'L' } },
  { Semicolon: { id: 'Semicolon', name: ';', shiftName: ':' } },
  { Quote: { id: 'Quote', name: '\'', shiftName: '"' } },
  { Enter: { id: 'Enter', name: 'enter' } },
];

export const FOURTH_ROW = [
  { ShiftLeft: { id: 'ShiftLeft', name: 'shift' } },
  { KeyZ: { id: 'KeyZ', name: 'z', shiftName: 'Z' } },
  { KeyX: { id: 'KeyX', name: 'x', shiftName: 'X' } },
  { KeyC: { id: 'KeyC', name: 'c', shiftName: 'C' } },
  { KeyV: { id: 'KeyV', name: 'v', shiftName: 'V' } },
  { KeyB: { id: 'KeyB', name: 'b', shiftName: 'B' } },
  { KeyN: { id: 'KeyN', name: 'n', shiftName: 'N' } },
  { KeyM: { id: 'KeyM', name: 'm', shiftName: 'M' } },
  { Comma: { id: 'Comma', name: ',', shiftName: '<' } },
  { Period: { id: 'Period', name: '.', shiftName: '>' } },
  { Slash: { id: 'Slash', name: '/', shiftName: '?' } },
  { ArrowUp: { id: 'ArrowUp', name: '▲' } },
  { ShiftRight: { id: 'ShiftRight', name: 'shift' } },
];

export const FIFTH_ROW = [
  { ControlLeft: { id: 'ControlLeft', name: 'control' } },
  { AltLeft: { id: 'AltLeft', name: 'alt' } },
  { MetaLeft: { id: 'MetaLeft', name: 'command' } },
  { Space: { id: 'Space', name: ' ' } },
  { MetaRight: { id: 'MetaRight', name: 'command' } },
  { AltRight: { id: 'AltRight', name: 'alt' } },
  { ArrowLeft: { id: 'ArrowLeft', name: '◀' } },
  { ArrowDown: { id: 'ArrowDown', name: '▼' } },
  { ArrowRight: { id: 'ArrowRight', name: '▶' } },
];

export const KEYS_TO_IGNORE_VALUE = {
  CapsLock: 'CapsLock',
  Enter: 'Enter',
  ShiftLeft: 'ShiftLeft',
  ShiftRight: 'ShiftRight',
  ControlLeft: 'ControlLeft',
  AltLeft: 'AltLeft',
  MetaLeft: 'MetaLeft',
  MetaRight: 'MetaRight',
  AltRight: 'AltRight',
  Backspace: 'Backspace',
};
