export const FIRST_ROW = [
  { Backquote: { id: 'Backquote', name: '`' } },
  { Digit1: { id: 'Digit1', name: '1' } },
  { Digit2: { id: 'Digit2', name: '2' } },
  { Digit3: { id: 'Digit3', name: '3' } },
  { Digit4: { id: 'Digit4', name: '4' } },
  { Digit5: { id: 'Digit5', name: '5' } },
  { Digit6: { id: 'Digit6', name: '6' } },
  { Digit7: { id: 'Digit7', name: '7' } },
  { Digit8: { id: 'Digit8', name: '8' } },
  { Digit9: { id: 'Digit9', name: '9' } },
  { Digit0: { id: 'Digit0', name: '0' } },
  { Minus: { id: 'Minus', name: '-' } },
  { Equal: { id: 'Equal', name: '=' } },
  { Backspace: { id: 'Backspace', name: 'delete' } },
];

export const SECOND_ROW = [
  { Tab: { id: 'Tab', name: 'tab' } },
  { KeyQ: { id: 'KeyQ', name: 'Q' } },
  { KeyW: { id: 'KeyW', name: 'W' } },
  { KeyE: { id: 'KeyE', name: 'E' } },
  { KeyR: { id: 'KeyR', name: 'R' } },
  { KeyT: { id: 'KeyT', name: 'T' } },
  { KeyY: { id: 'KeyY', name: 'Y' } },
  { KeyU: { id: 'KeyU', name: 'U' } },
  { KeyI: { id: 'KeyI', name: 'I' } },
  { KeyO: { id: 'KeyO', name: 'O' } },
  { KeyP: { id: 'KeyP', name: 'P' } },
  { BracketLeft: { id: 'BracketLeft', name: '[' } },
  { BracketRight: { id: 'BracketRight', name: ']' } },
  { Backslash: { id: 'Backslash', name: '\\' } },
];

export const THIRD_ROW = [
  { CapsLock: { id: 'CapsLock', name: 'caps lock' } },
  { KeyA: { id: 'KeyA', name: 'A' } },
  { KeyS: { id: 'KeyS', name: 'S' } },
  { KeyD: { id: 'KeyD', name: 'D' } },
  { KeyF: { id: 'KeyF', name: 'F' } },
  { KeyG: { id: 'KeyG', name: 'G' } },
  { KeyH: { id: 'KeyH', name: 'H' } },
  { KeyJ: { id: 'KeyJ', name: 'J' } },
  { KeyK: { id: 'KeyK', name: 'K' } },
  { KeyL: { id: 'KeyL', name: 'L' } },
  { Semicolon: { id: 'Semicolon', name: ';' } },
  { Quote: { id: 'Quote', name: '\'' } },
  { Enter: { id: 'Enter', name: 'enter' } },
];

export const FOURTH_ROW = [
  { ShiftLeft: { id: 'ShiftLeft', name: 'shift' } },
  { KeyZ: { id: 'KeyZ', name: 'Z' } },
  { KeyX: { id: 'KeyX', name: 'X' } },
  { KeyC: { id: 'KeyC', name: 'C' } },
  { KeyV: { id: 'KeyV', name: 'V' } },
  { KeyB: { id: 'KeyB', name: 'B' } },
  { KeyN: { id: 'KeyN', name: 'N' } },
  { KeyM: { id: 'KeyM', name: 'M' } },
  { Comma: { id: 'Comma', name: ',' } },
  { Period: { id: 'Period', name: '.' } },
  { Slash: { id: 'Slash', name: '/' } },
  { ArrowUp: { id: 'ArrowUp', name: '▲' } },
  { ShiftRight: { id: 'ShiftRight', name: 'shift' } },
];

export const FIFTH_ROW = [
  { ControlLeft: { id: 'ControlLeft', name: 'control' } },
  { AltLeft: { id: 'AltLeft', name: 'alt' } },
  { MetaLeft: { id: 'MetaLeft', name: 'command' } },
  { Space: { id: 'Space', name: ' ' } },
  { MetaRight: { id: 'MetaRight', name: 'command' } },
  { AltRight: { id: 'AltRight', name: 'alt' } },
  { ArrowLeft: { id: 'ArrowLeft', name: '◀' } },
  { ArrowDown: { id: 'ArrowDown', name: '▼' } },
  { ArrowRight: { id: 'ArrowRight', name: '▶' } },
];
